# Generated by Django 2.2.3 on 2019-08-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190802_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='cnpj',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='cnpj'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='nome_empresa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome'),
        ),
    ]
