# Generated by Django 2.2.4 on 2019-08-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190804_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('genero', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outros')], max_length=255, verbose_name='Gênero')),
                ('cpf', models.CharField(max_length=255, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=255, verbose_name='Telefone Fixo')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha')),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.RenameField(
            model_name='instituicao',
            old_name='endereco',
            new_name='rua',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='numero',
        ),
        migrations.AddField(
            model_name='instituicao',
            name='complemento',
            field=models.CharField(default='apt', max_length=6, verbose_name='Complemento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instituicao',
            name='uf',
            field=models.CharField(default='sp', max_length=100, verbose_name='UF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='Endereço'),
        ),
    ]
