# Generated by Django 2.2.4 on 2019-08-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190808_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='telefone_comercial',
            field=models.CharField(default='phone number', max_length=255, verbose_name='Telefone Comercial'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='bairro',
            field=models.CharField(max_length=255, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='cep',
            field=models.CharField(max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='cnpj',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='complemento',
            field=models.CharField(max_length=255, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='municipio',
            field=models.CharField(max_length=255, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='rua',
            field=models.CharField(max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='uf',
            field=models.CharField(max_length=255, verbose_name='UF'),
        ),
    ]
